name: Integration Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '10'  # See https://hub.docker.com/_/postgres for available versions
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run Tests
        run: .travis/stages/verify/integration-testing/run

